apiVersion: v2
name: vault-monitoring
description: monitor your vault server from within Kubernetes' prometheus
type: application
version: 0.3.2
home: https://github.com/adfinis/helm-charts/tree/main/charts/vault-monitoring
sources:
  - https://github.com/adfinis/helm-charts/tree/main/charts/vault-monitoring
maintainers:
  - name: adfinis
    email: support@adfinis.com
    url: https://adfinis.com
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "Add new metric for vault"
