apiVersion: v2
name: vault-monitoring
description: monitor your vault server from within Kubernetes' prometheus
type: application
version: 0.2.0
home: https://github.com/adfinis-sygroup/helm-charts/tree/master/charts/vault-monitoring
sources:
  - https://github.com/adfinis-sygroup/helm-charts/tree/main/charts/vault-monitoring
maintainers:
  - name: adfinis-sygroup
    email: support@adfinis.com
    url: https://adfinis.com
