apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "timed.fullname" . }}-dbmigrate
  labels:
    {{- include "timed.labels" . | nindent 4 }}
    app.kubernetes.io/component: db-migrate
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  activeDeadlineSeconds: 300
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        {{- include "timed.labels" . | nindent 8 }}
        app.kubernetes.io/component: db-migrate
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}-dbmigrate
          image: "{{ .Values.backend.image.repository }}:{{ default .Chart.AppVersion .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          env:
            - name: DJANGO_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "timed.postgresql.fullname" . }}
                  key: postgresql-password
          envFrom:
            - secretRef:
                name: {{ include "timed.fullname" . }}-backend
            - configMapRef:
                name: {{ include "timed.fullname" . }}-backend
          command: ["./manage.py", "migrate"]
