apiVersion: v2
name: huawei-csi-plugin
description: Deploy the Huawei CSI plugin
type: application
version: 0.0.1
appVersion: v2.2.RC3
home: https://github.com/Huawei/eSDK_K8S_Plugin
sources:
  - https://github.com/Huawei/eSDK_K8S_Plugin
  - https://github.com/adfinis-sygroup/huawei-csi-plugin
  - https://github.com/adfinis-sygroup/helm-charts/tree/master/charts/huawei-csi-plugin
maintainers:
  - name: adfinis-sygroup
    email: support@adfinis.com
    url: https://adfinis.com
