{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kasperleyn.serviceAccountName" . }}
  labels:
{{ include "kasperleyn.labels" . | indent 4 }}
{{- end -}}
