apiVersion: v2
name: cert-manager-issuers
description: Configure cert-manager Issuers and ClusterIssuers via Helm
type: application
version: 0.2.0
# matches apiVersion: cert-manager.io/v1
appVersion: "1"
home: https://cert-manager.io/docs/configuration/
icon: https://raw.githubusercontent.com/adfinis-sygroup/helm-charts/master/charts/cert-manager-issuers/logo.png
sources:
  - https://github.com/adfinis-sygroup/helm-charts
maintainers:
  - name: adfinis-sygroup
    email: support@adfinis.com
    url: https://adfinis.com
dependencies:
  - name: common
    repository: https://charts.adfinis.com
    version: 0.0.6
