apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rmd.fullname" . }}
  labels:
    {{- include "rmd.labels" . | nindent 4 }}
    app.kubernetes.io/component: rmd
type: Opaque
data:
  {{ if .Values.rmd.service.secret }}
  DJANGO_SECRET_KEY: {{ .Values.rmd.service.secret | b64enc | quote }}
  {{ else }}
  DJANGO_SECRET_KEY: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end }}
