spec:
  metadata:
    # spec.metadata.name -- name for the ArgoCD application
    name: sentry
    # spec.metadata.namespace -- namespace for the ArgoCD application
    namespace: argocd
  destination:
    # spec.destination.namespace -- namespace for Sentry
    namespace: sentry
  # spec.project -- project to deploy the ArgoCD application to
  project: default
  source:
    # spec.source.chart -- name of the Chart for Sentry
    chart: sentry
    # spec.source.path -- path of the Chart for Sentry when using Git repository
    path: ""
    # spec.source.repoURL -- Chart museum to get Sentry
    repoURL: "https://sentry-kubernetes.github.io/charts"
    # spec.source.targetRevision -- revision of the chart to use for Sentry
    # @default -- current appVersion
    targetRevision: ""

user:
  # user.create -- if true, creates the user defined by email and password.
  create: true
  # user.email -- Super user email
  email: admin@sentry.local
  # user.password -- Super user password.
  # @default -- A randomly generated one.
  password: ""

ingress:
  # ingress.enabled -- if true, enables the ingress configuration.
  enabled: false
  # ingress.hostname -- hostname to use
  hostname: ""

clickhouse:
  # clickhouse.replicas -- total number of clickhouse replicas
  replicas: 1

# kakfa -- Kafka configuration
# @default -- See [sentry's default](https://github.com/sentry-kubernetes/charts/blob/develop/sentry/values.yaml) or [bitnami/kafka](https://github.com/bitnami/charts/tree/master/bitnami/kafka/)
kafka:
  # kafka.replicaCount -- number of Kakfa brokers to deploy
  replicaCount: 1
  # kafka.defaultReplicationFactor -- replication factor for automatically created topics
  defaultReplicationFactor: 1
  # kafka.offsetsTopicReplicationFactor -- replication factor for the offsets topic
  offsetsTopicReplicationFactor: 1
  # kafka.transactionStateLogReplicationFactor -- replication factor for the transaction topic
  transactionStateLogReplicationFactor: 1
  # kafka.transactionStateLogMinIsr -- overridden min.insync.replicas config for the transaction topic
  transactionStateLogMinIsr: 1

# nginx -- NGINX configuration (required when `ingress.enabled=false`)
# @default -- See [sentry's default](https://github.com/sentry-kubernetes/charts/blob/develop/sentry/values.yaml)
nginx:
  # nginx.enabled -- enables nginx
  enabled: true

rabbitmq:
  # rabbitmq.enabled -- enable RabbitMQ
  # Redis will be used instead.
  enabled: false

relay:
  # relay.replicas -- total number of relay replicas (use 0 when bootstrapping)
  replicas: 1

# redis -- Redis settigs
# @default -- See [bitnami/redis](https://github.com/bitnami/charts/tree/master/bitnami/redis) chart
redis:
  enabled: true

  cluster:
    # redis.cluster.slaveCount -- number of followers in the Redis cluster
    slaveCount: 1

sentry:
  worker:
    # sentry.worker.replicas -- total number of sentry worker replicas
    replicas: 1

postgresql:
  # postgresql.postgresqlPassword -- (string) password used to access the database
  postgresqlPassword:
  persistence:
    # postgresql.persistence.enabled -- Enable postgresql persistence
    enabled: true

# config -- extra configuration for some config maps
# @default -- See [values.yaml](https://github.com/sentry-kubernetes/charts/tree/develop/sentry) of upstream project
config: {}

system:
  # system.secretKey -- (string) secret key used for the session.
  # Changing it invalidates all the current sessions.
  secretKey:
