apiVersion: v2
name: osschallenge
description: Chart for OSS-Challenge application
type: application
version: 0.1.2
appVersion: edge
keywords:
  - osschallenge
  - postgresql
home: https://oss-challenge.ch
sources:
  - https://github.com/adfinis-sygroup/osschallenge
  - https://github.com/adfinis-sygroup/helm-charts/tree/master/charts/osschallenge
maintainers:
  - name: adfinis-sygroup
    email: support@adfinis.com
    url: https://adfinis.com
dependencies:
  - name: postgresql
    version: ~10.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
