apiVersion: v2
name: openshift-etcd-backup
description: Chart for openshift-etcd-backup solution
type: application
version: 1.9.7
appVersion: v1.9.7
keywords:
  - openshift-etcd-backup
  - openshift
  - backup
  - etcd
home: https://github.com/adfinis/openshift-etcd-backup
sources:
  - https://github.com/adfinis/openshift-etcd-backup
  - https://github.com/adfinis/helm-charts/tree/main/charts/openshift-etcd-backup
maintainers:
  - name: adfinis
    email: support@adfinis.com
    url: https://adfinis.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: |
        upgrade openshift-etcd-backup image to v1.9.6
        * set pod's dns policy to ClusterFirstWithHostNet

      links:
        - name: openshift-etcd-backup release v1.9.7
          url: https://github.com/adfinis/openshift-etcd-backup/releases/tag/v1.9.7
