---
apiVersion: v2
name: kubernetes-etcd-backup
description: Chart for kubernetes-etcd-backup solution
type: application
version: 1.5.0
appVersion: v1.2.1
keywords:
  - kubernetes-etcd-backup
  - kubernetes
  - backup
  - etcd
home: https://github.com/adfinis/kubernetes-etcd-backup
sources:
  - https://github.com/adfinis/kubernetes-etcd-backup
maintainers:
  - name: adfinis
    email: support@adfinis.com
    url: https://adfinis.com
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |
    - kind: changed
      description: "Add support for s3 storage"
      links:
        - name: "kubernetes-etcd-backup v1.3.1"
          url: https://github.com/adfinis/kubernetes-etcd-backup/releases/tag/v1.3.1
