apiVersion: v2
name: kubernetes-etcd-backup
description: Chart for kubernetes-etcd-backup solution
type: application
version: 1.0.0
appVersion: v1.0.4
keywords:
  - kubernetes-etcd-backup
  - kubernetes
  - backup
  - etcd
home: https://github.com/adfinis/kubernetes-etcd-backup
sources:
  - https://github.com/adfinis/kubernetes-etcd-backup
maintainers:
  - name: adfinis
    email: support@adfinis.com
    url: https://adfinis.com
