apiVersion: v2
name: keycloak-operator
description: Deploy Keycloak Operator and Keycloak
type: application
version: 0.1.0
appVersion: "21.0.2"
home: https://www.keycloak.org
sources:
  - https://github.com/keycloak/keycloak-k8s-resources
  - https://github.com/adfinis/helm-charts/tree/main/charts/keycloak-operator
maintainers:
  - name: adfinis
    email: support@adfinis.com
    url: https://adfinis.com
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: initial version of keycloak-operator chart
