apiVersion: v2
name: keycloak-operator
description: Deploy Keycloak Operator and Keycloak
type: application
version: 1.3.0
appVersion: "24.0.4"
icon: https://www.keycloak.org/resources/images/logo-stacked.svg
home: https://www.keycloak.org
sources:
  - https://github.com/keycloak/keycloak-k8s-resources
  - https://github.com/adfinis/helm-charts/tree/main/charts/keycloak-operator
maintainers:
  - name: adfinis
    email: support@adfinis.com
    url: https://adfinis.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "New feature: customise namespace"
      links:
        - name: "Issue 1273"
          url: https://github.com/adfinis/helm-charts/issues/1273
