lokiStack:
  enabled: false
  values: {}

loki:
  enabled: true
  values: {}

promtail:
  enabled: true
  values: {}

filebeat:
  enabled: true
  values: {}

fluentd:
  enabled: true
  values: {}

fluent-bit:
  enabled: true
  values: {}

opentelemetryCollectorEvents:
  enabled: true
  values: {}

opentelemetryCollectorLogs:
  enabled: true
  values: {}
