apiVersion: v2
name: azure-apps
description: Argo CD app-of-apps config for Azure applications
type: application
version: 0.16.1
home: https://github.com/adfinis/helm-charts/tree/main/charts/azure-apps
sources:
  - https://github.com/adfinis/helm-charts
maintainers:
  - name: adfinis
    email: support@adfinis.com
    url: https://adfinis.com
dependencies:
  - name: argoconfig
    version: 0.9.1
    repository: https://charts.adfinis.com
annotations:
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/changes: |
    - kind: security
      description: |
        Update promitorResourceDiscovery to 0.14.1, which includes patches for various CVEs.
      links:
        - name: Promitor Resource Discovery v0.14.1
          url: https://github.com/tomkerkhove/promitor/releases/tag/ResourceDiscovery-v0.14.1
        - name: ResourceDiscovery v0.14.1
          url: https://github.com/promitor/charts/releases/tag/ResourceDiscovery-v0.14.1
