apiVersion: v2
name: back8sup
description: Deploy back8sup to a Kubernetes Cluster
type: application
version: 0.1.3
appVersion: v0.1.0
home: https://github.com/adfinis-sygroup/back8sup
sources:
  - https://github.com/adfinis-sygroup/back8sup
  - https://github.com/adfinis-sygroup/helm-charts/tree/master/charts/back8sup
maintainers:
  - name: adfinis-sygroup
    email: support@adfinis.com
    url: https://adfinis.com
