apiVersion: v2
name: storage-apps
description: Argo CD app-of-apps config for storage applications
type: application
version: 0.20.0
home: https://github.com/adfinis/helm-charts/tree/main/charts/storage-apps
sources:
  - https://github.com/adfinis/helm-charts
maintainers:
  - name: adfinis
    email: support@adfinis.com
    url: https://adfinis.com
dependencies:
  - name: argoconfig
    version: 0.9.1
    repository: https://charts.adfinis.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: |
        Updated cephCsiCephfs and cephCsiRbd charts to 3.15.1, including:
          - Bug/fencing shallow volume
          - Fix bug where volumereplication promote/demote would fail
          - Support compressed ipv6 addresses
          - skip reset quiesce during DeleteVolumeGroupSnapshot
          - retry controllerpublish secret fetch on missing clusterId
          - pass fsName when mounting from monitor list
      links:
        - name: "3.15.1 Release Notes"
          url: "https://github.com/ceph/ceph-csi/releases/tag/v3.15.1"
