apiVersion: v2
name: storage-apps
description: Argo CD app-of-apps config for storage applications
type: application
version: 0.20.0
home: https://github.com/adfinis/helm-charts/tree/main/charts/storage-apps
sources:
  - https://github.com/adfinis/helm-charts
maintainers:
  - name: adfinis
    email: support@adfinis.com
    url: https://adfinis.com
dependencies:
  - name: argoconfig
    version: 0.9.1
    repository: https://charts.adfinis.com
annotations:
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/changes: |
    - kind: changed
      description: |
        Updated csiDriverSmb to 1.19.1, including:
          - Various CVE fixes
          - upgrade csi-resizer to v1.14.0
          - enable to use secrets with special characters
          - support multiple storage classes creation using helm chart
      links:
        - name: "v1.19.1 Release Notes"
          url: "https://github.com/kubernetes-csi/csi-driver-smb/releases/tag/v1.19.1"
        - name: "v1.19.0 Release Notes"
          url: "https://github.com/kubernetes-csi/csi-driver-smb/releases/tag/v1.19.0"
