dex:
  enabled: true
  values: {}

vault:
  enabled: true
  values: {}

falco:
  enabled: true
  values: {}

falcoExporter:
  enabled: true
  value: {}

gatekeeper:
  enabled: true
  values: {}

vaultMonitoring:
  enabled: true
  values: {}

secretsStoreCsiDriver:
  enabled: true
  values: {}

neuvector:
  enabled: true
  values: {}

neuvectorMonitor:
  enabled: true
  values: {}

oauth2-proxy:
  enabled: true
  values: {}

kyverno:
  enabled: true
  values: {}

kyvernoPolicies:
  enabled: true
  values: ()
