name: Helm Chart Version Checker

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 1 * *'

jobs:
  check_versions:
    name: Check for new Helm chart versions
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Run Helm Version Checker
        uses: adfinis/helm-version-checker@v2.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          maintainers_file: 'MAINTAINERS.yaml'
