{{- if .Values.operator.enabled }}
{{- if .Values.operator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keycloak-operator.operator.serviceAccountName" . }}
  {{- with .Values.operator.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "keycloak-operator.operator.labels" . | nindent 4 }}
  {{- with .Values.operator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
